name: iOS Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        
    - name: Get Flutter dependencies
      run: flutter pub get
      
    - name: Run Flutter tests
      run: flutter test
      
    - name: Build iOS app
      run: |
        flutter clean
        flutter pub get
        cd ios
        pod install
        cd ..
        flutter build ios --release --no-codesign
      env:
        IPHONEOS_DEPLOYMENT_TARGET: 13.0
        
    - name: Create IPA file
      run: |
        mkdir -p Payload
        cp -r build/ios/iphoneos/Runner.app Payload/
        zip -r Runner.ipa Payload
        rm -rf Payload
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: Runner.ipa